### ISSUE TITLE
Sugary syntax version

### ISSUE THREAD

**Issue by alskipp** [RuiAAPeres/OptionalExtensions#4]
This is not an issue! 

I'm just interested in your opinion of the code below, it adds no additional functionality, hence, not an issue. As an exercise for my own entertainment, I've created a version of the extension that utilises as much sugary syntax as I could muster (using single expressions per function and using `if case` syntax when apt, etc). 

Your original is written in a clear, explicit style which is easy to decipher, the version below is undoubtedly more cryptic (one thing I do like is that each function contains one expression and one `return` statement, but it is arguable how important that is). I think the versions of `onSome` and `onNone` would fit with the current style, but the others are a bit of a departure.

Anyway, I thought I'd throw it out there to see what you thought.

All the best,
Al

``` swift

public extension Optional {
    func filter(@noescape predicate: Wrapped -> Bool) -> Optional {
        return map(predicate) == .Some(true) ? self : .None
    }

    func replaceNil(with replacement: Wrapped) -> Optional {
        return self ?? replacement
    }

    func apply(@noescape f: Wrapped -> Void) {
        if case let wrapped? = self { f(wrapped) }
    }

    func onSome(@noescape f: Wrapped -> Void) -> Optional {
        apply(f)
        return self
    }

    func onNone(@noescape f: Void -> Void) -> Optional {
        if isNone { f() }
        return self
    }

    var isSome: Bool {
        return map { _ in true } ?? false
    }

    var isNone: Bool {
        return !isSome
    }
}
```

**Comment by RuiAAPeres** [comment]
Actually, I prefer it like this (but I am bit biased, as I love terse code). :/

**Comment by RuiAAPeres** [comment]
I was unaware of this:

```
if case let wrapped? = self { f(wrapped) }
```

**Comment by alskipp** [comment]
> I was unaware of this:
> 
> ```
>   if case let wrapped? = self { f(wrapped) }
> ```

It's something I've rarely used (and can never remember the syntax for!). I think it's only really useful when you want to perform a side-effect when there's a wrapped value and ignore the `None` case – so it's quite apt here.

**Comment by alskipp** [comment]
Come to think of it, there's no need to use `if case let` syntax here (what was I thinking?) the usual `if let` will do perfectly fine. I imagine it's only there because of `for case let`, which I'm opposed to on religious grounds : ) There's so much Optional sugar sprinkled about in Swift, it's easy to become confused due to hyperglycaemia!

**Comment by RuiAAPeres** [comment]
@alskipp So: 

```
 if case let wrapped? = self { f(wrapped) }
```

to:

```
 if let wrapped = self { f(wrapped) } 
```

**Comment by RuiAAPeres** [comment]
For the `isSome`, we could go with this:

```
    public var isSome: Bool {
        return self != nil
    }
```

**Comment by alskipp** [comment]
> For the isSome, we could go with this:
> 
> ```
>   public var isSome: Bool {
>       return self != nil
>   }
> ```

Well, that's much simpler! 

My natural inclination was to try `self != .None`, but that isn't possible because the wrapped value is not constrained by `Equatable`, so it's not possible to compare non-equatable Optionals.

Which means that `self != nil` is a peculiar operator override:  
`public func !=<T>(lhs: T?, rhs: _OptionalNilComparisonType) -> Bool`

`nil` is such a polymorphic beast in Swift!

**Comment by RuiAAPeres** [comment]
It's a weird one and I agree with you, there is tons of sugar everywhere. :-1:

**Comment by alskipp** [comment]
How about?

``` haskell
isJust         :: Maybe a -> Bool
isJust Nothing = False
isJust _       = True
```

😉

**Comment by RuiAAPeres** [comment]
the previous approach (I just pushed the change) was pretty much like that. :stuck_out_tongue:

**Comment by alskipp** [comment]
True! We just need pattern matching built into function definitions and we'll be sorted (I'm sure it'll only take a tiny change to the language 😬)

**Comment by RuiAAPeres** [comment]
Well sir, [be my guest](https://github.com/apple/swift#fork-destination-box).

**Comment by alskipp** [comment]
I'll have a cup of tea and think about it, then another cup, then… maybe I'll just stick with the tea drinking…

**Comment by RuiAAPeres** [comment]
@alskipp I am still happy to merge the proposed changed!

**Comment by alskipp** [comment]
If you're happy with the changes then I'll gladly make a PR. 

Just to double check, you're happy with the somewhat dense ternary expression in `filter`?
`return map(predicate) == .Some(true) ? self : .None`

**Comment by RuiAAPeres** [comment]
:+1:
